### ISSUE TITLE
Enhancement - Use npm module versions of vendor styles

### ISSUE THREAD

**Issue by BrianDGLS** [BrianDGLS/pops#16]
**Problem**: The `app/www/scss/vendor` files should not be static. 

The libraries used are 
 - [Tachyons](http://tachyons.io/)
 - [Colors](http://clrs.cc/)
 - [Prism](http://prismjs.com/)

**Solution**: Use the npm versions of these libraries.

-----------

Prism is already installed via npm, it is just a matter of updating the import in `app/www/scss/main.scss` to point to prismjs in the node_modules folder.

Webpack is used to compile the scss so it maybe a good idea to include some sort of path alias that uses the node_modules folder as an include path when looking for scss imports.

In order to build the forntend run `webpack` or `webpack --watch` in the root dir.

To quickly create a dev styleguide run the following in the projects root dir.
```
$ node app/bin/pops.js init
$ node app/bin/pops.js make::component test
$ node app/bin/pops.js serve
```

Then navigate to [http://127.0.0.1:9095](http://127.0.0.1:9095).

**Comment by ericorruption** [comment]
tried fixing this but don't know enough webpack to handle css and scss imports on the same file. 😢  will give it another try during this week though.

**Comment by BrianDGLS** [comment]
@ericorruption Nice one, feel free to open a pr with what you currently have,

**Comment by BrianDGLS** [comment]
Resolved
