### ISSUE TITLE
Feature - Upgrade to Vue 2.0.0

### ISSUE THREAD

**Issue by BrianDGLS** [BrianDGLS/pops#8]
Pops should use Vue 2.0.0 for it's frontend. It currently uses Vue ^1.0.0.

Upgrading to Vue 2 may be as simple as updating the project's `package.json` file. If there are errors however. The Vue frontend can be found in the `pops/app/www` folder.

In order to build the frontend run `webpack` or `webpack --watch` in the project's root. Then server the styleguide using `node app/bin/pops.js serve` or `pops serve` if it is installed globally.

**Comment by Klowner** [comment]
:jack_o_lantern:

**Comment by BrianDGLS** [comment]
Resolved with #12
